server:
  port: 8089

spring:
  profiles:
    active: dev
  thymeleaf:
      #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
      #编码 可不用配置
    encoding: UTF-8
      #内容类别,可不用配置
    cache: false
      #配置模板路径，默认是templates，可以不用配置
#    prefix: classpath:/templates
    servlet:
      content-type: text/html


# MyBatis
mybatis:
  typeAliasesPackage: com.garben.**.entity

  mapperLocations: classpath*:mapper/*Mapper.xml

#  configLocation: classpath*:mybatis/mybatis-config.xml

logging:
  level:
    com.garben: debug
    springbootDemo: debug

###ThymeLeaf配置




#debug: true
